### PR TITLE
Add Guix Alternative Installation to README

### PR DESCRIPTION
**Pull request by jgarte**
Hi,

I packaged bower 0.13 for guix and put it in a pre-release channel called [GuixRUS](https://git.sr.ht/~whereiseveryone/guixrus/commit/389dc1db8379d59d50041284b7fe3f59a28f9c23) that I maintain with some other guix upstream contributors.

All commits are gpg signed by the maintainers.

Next, I'll send a patch upstream and wait for review and merge.

In the meantime, the `GuixRUS` channel is available. We'll also be offering a public binary server (substitute server in guix jargon) for the channel (TBA).

I [also maintain](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/networking/mailreaders/notmuch-bower/default.nix#L34) the nix package for bower. 

Tests are enabled for the guix package but not for the nix package currently.

I'll look to enabling tests for the nix bower package next.

```
 _________________________________________ 
/ 3B1D 7F19 E36B B60C 0F5B 2CA9 A52A A2B4 \
\ 77B6 DD35                               /
 ----------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### CODE REVIEW

**Comment by wangp** [comment]
Perhaps we can just write this:

    Packages are also available in [AUR], [Gentoo], [GuixRUS], [Nixpkgs].

to avoid loading the README with distro specifics.

**Comment by jgarte** [comment]
> Perhaps we can just write this:
> 
> ```
> Packages are also available in [AUR], [Gentoo], [GuixRUS], [Nixpkgs].
> ```
> 
> to avoid loading the README with distro specifics.

Sure, that sounds good to me.

**Comment by jgarte** [comment]
I added a new commit with the change that you requested.

**Comment by wangp** [comment]
Thanks, I've merged it.

**Pull request closed without merging**
